### ISSUE TITLE
Missing translation - ข้อความที่ไม่ได้แปล ใน เผ่าพันธ์ -> รูปลักษณ์

### ISSUE THREAD

**Issue by PhakphumV** [pongmadee/Stellaris-Thai-Translation-MOD#2]
สวัสดีครับ มีพบข้อความที่ยังไม่ได้แปลใน เผ่าพันธ์ -> รุปลักษณ์ เวลาสร้างจักรวรรดิใหม่นะครับ
Mod v0.71.4, Update 15/12/2023

มีคำศัพท์ดังนี้นะครับ

- Necroid เนื้อร้าย (ถ้าแปลตรงตัว)
- Aquatic สัตว์น้ำ หรือ น้ำ
- Toxoid ทอกซอยด์

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/3d315318-1a97-4568-a0ad-0ce391c98145)

**Comment by pongmadee** [comment]
ขอบคุณครับ รับทราบครับ 
- Necroid ในความคิดส่วนตัว ใช้ทับศัพท์น่าจะเหมาะกว่านะ

**Comment by PhakphumV** [comment]
> ขอบคุณครับ รับทราบครับ
> 
>     * Necroid ในความคิดส่วนตัว ใช้ทับศัพท์น่าจะเหมาะกว่านะ

ได้นะครับ ถ้าทับศัพท์มันจะเป็น "เนครอยด์" นะครับ

**Comment by pongmadee** [comment]
แก้ลง patch หน้าครับ เพื่อเป็นการขอบคุณ เดี๋ยวผมขึ้นเคดิตชื่อไว้ให้ใน patch นะครับ คุณ [PhakphumV](https://github.com/PhakphumV)

**Comment by PhakphumV** [comment]
ยินดีครับผม เดี๋ยวจะมาตรวจและมาช่วยแจ้งคำแปลให้ในจุดอื่นๆด้วยนะครับ 
ส่วนเครดิต ใส่เป็นช่อง youtube ของผมด้วยได้มั้ยครับ ชื่อ ZFox Gaming
https://www.youtube.com/channel/UCGO2v4qXvUMzYQBwmi69t6Q

**Comment by pongmadee** [comment]
> ยินดีครับผม เดี๋ยวจะมาตรวจและมาช่วยแจ้งคำแปลให้ในจุดอื่นๆด้วยนะครับ ส่วนเครดิต ใส่เป็นช่อง youtube ของผมด้วยได้มั้ยครับ ชื่อ ZFox Gaming https://www.youtube.com/channel/UCGO2v4qXvUMzYQBwmi69t6Q

ได้เลยครับ

**Comment by PhakphumV** [comment]
ตรวจสอบแล้วครับ คำแปลขึ้นครบถ้วน
