### ISSUE TITLE
Missing translation - Origin

### ISSUE THREAD

**Issue by PhakphumV** [pongmadee/Stellaris-Thai-Translation-MOD#4]
สวัสดีครับ มีพบข้อความที่ยังไม่ได้แปลใน "จุดเริ่มต้น" เวลาสร้างจักรวรรดิใหม่นะครับ
Mod v0.71.4, Update 15/12/2023

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/4dbb6ea7-43f1-403a-89e0-bbb388aafdcf)

มีดังนี้
- Knights of the Toxic God อัศวินของเทพทรพิษ
  - คำอธิบาย : เมื่อหลายทศวรรศก่อน มีเอนทิตี้ (Entity ไม่รู้ว่าควรแปลว่าอะไรดี) เคยมาเยือนและสร้างมหันตภัยที่ทำลายโลกไปครึ่งหนึ่ง เหลือไว้อีกครึ่งให้กับเหล่าพลเมืองที่บูชาเอนทิตี้นี้เป็นเทพทรพิษของพวกเขา ภาคีอัศวินได้ถูกก่อตั้งขึ้นเพื่อออกตามหาเทพของพวกเขาในอวกาศอันกว้างใหญ่นี้

- Payback เอาคืน
  - คำอธิบาย : อารยธรรมนี้มีต่างดาวได้เคยมาเยือนและบังคับกดขี่ไว้ แต่พวกเขาขับไล่ผู้บุกรุกได้ แต่ว่าผู้บุกรุกนี้จะกลับมาอีกหรือไม่

- Broken Shackles โซ่ตรวนที่แตกหัก
  - คำอธิบาย : เป็นเหล่าทาสที่หลากหลายเผ่าพันธ์หลบหนีจากยานขนทาสและมาสร้างอารยธรรมของตนเอง

- Fear of the Dark หวาดกลัวความมืด
  - คำอธิบาย : เมื่อทศวรรษก่อน ดาวบ้านเกิดเดิมถูกทำลายด้วยอุกกาบาต ซึ่งความเห็นประชากรกลุ่มหนึ่งก็เชื่อว่าเป็นการโจมตีจากต่างดาว ทำให้มี
ความตึงเครียดและหวาดระแวงต่อโลกภายนอก

- Fruitful Partnership : หุ้นส่วนที่ออกดอกออกผล
  - คำอธิบาย : เป็นอารยธรรมที่มีการร่วมทำงานกันกับสิ่งมีชีวิตในอวกาศทำให้เมล็ดพันธ์ที่ช่วยขยายอาณานิคมของพวกเขาได้

- Riftworld : *อันนี้น่าจะทับศัพท์ไปเลย*
  - คำอธิบาย : เป็นอารยธรรมที่มีรอยแยกมิติอวกาศและกาลเวลาใกล้ดาวบ้านเกิด ทำให้มีการศึกษาปรากฏการณ์มาอย่างช้านานจนมีเทคโนโลยีที่สามารถใช้สำรวจและค้นหาความลับในรอยแยกเหล่านี้ได้

ปล. คำแปลและคำอธิบาย ลองไปปรับดูได้นะครับ ผมพยายามปรับให้มันเข้าใจง่าย แต่อาจจะไม่ครอบคลุมเนื้อหาบางส่วนไปนะครับ

**Comment by pongmadee** [comment]
ได้ครับ

**Comment by PhakphumV** [comment]
![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/b39a290f-ec17-4bf1-8d2e-21e8fec7d54d)

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/b5942e24-eaf4-47c6-a22a-ed4c6a266256)

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/2e34d417-b5cd-42f3-b108-fec585dcd654)

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/51c7b391-5382-46c7-9f33-472bbadf720c)

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/9dbc7ba8-496a-42eb-ba8a-1fb084c66ab2)

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/55345a81-55fa-4604-b00d-1822e3e9ffda)


ตรวจสอบเรียบร้อยครับ คำแปลขึ้นครบถ้วน สุดยอดมากครับ
