### ISSUE TITLE
Missing translation - Civics (พลเมือง)

### ISSUE THREAD

**Issue by PhakphumV** [pongmadee/Stellaris-Thai-Translation-MOD#5]
Mod version 0.71.5 

ในหน้าสร้างเผ่าพันธ์ใหม่ -> การปกครองและจริยธรรม ตรงส่วน "พลเมือง" หรือ Civics
พบคำที่ยังไม่แปลดังนี้นะครับ ขอเปิด issue ไว้ก่อน แล้วจะมาช่วยแปลให้นะครับ

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/6a4a2a04-938d-4909-8500-71d265dcc330)

## สำหรับระบอบการปกครองธรรมดา

- Dark consortium
- Hyperspace Specialty
- Mutagenic Spas
- Selective Kinship
- Dimensional Worship
- Relentless Industrialists
- Sovereign Guardianship

## สำหรับระบอบการปกครองแบบ จิตสำนึกร่วม

- Guardian Cluster
- Hyperspace Synchronicity
- Permutation Pools
- Stargazers
- Void Hive
- 

## สำหรับระบอบการปกครองแบบ สติปัญญาจักรกล

- Guardian Matrix
- Hyper Lubrication Basin
- Hyperspace Synchronicity

## สำหรับระบอบการปกครองแบบ บริษัท

- Catalytic Recyclers
- Hyperspace Trade
- Mastercraft Inc
- Mutagenic Spas
- Privatized Exploration
- Refurbishment Division
- Shadow Corporation
- Trawling Operations

Civics อื่นที่ได้ระหว่างเกมส์
![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/7a32ab54-7522-4ead-a962-c8771a4046ef)

- Galactic Sovereign 
- Divine Sovereign 
- Corporate Sovereign

**Comment by PhakphumV** [comment]
สำหรับระบอบการปกครองธรรมดา

- Dark consortium : สมาคมมืด
- Hyperspace Specialty : ชำนาญการไฮเปอร์สเปซ
- Mutagenic Spas : สปาก่อกลายพันธุ์
- Selective Kinship : เครือญาติคัดสรร
- Dimensional Worship : บูชาข้ามมิติ
- Relentless Industrialists : นักอุตสาหกรรมที่ไม่หยุดยั้ง
- Sovereign Guardianship : ผู้พิทักษ์อธิปไตย

**Comment by PhakphumV** [comment]
## สำหรับระบอบการปกครองธรรมดา

- Dark consortium : สมาคมสสารมืด
  - คำอธิบาย : คำว่า consortium แปลได้หลายอย่างอยู่ เช่น สมาคม กลุ่มบริษัท กิจการค้าร่วม
  - อ้างอิงศัพท์ จาก
    - https://www.dlo.co.th/business-articles/2358
    - https://finance.oou.cmu.ac.th/?q=th/node/26705
    - https://www.d1asia.co.th/newsroom/news-and-updates/joint-venture-consortium
  - ส่วน Dark มาจาก Dark matter 

- Hyperspace Specialty : ชำนาญการไฮเปอร์สเปซ
- Mutagenic Spas : สปาก่อกลายพันธุ์
- Selective Kinship : เครือญาติคัดสรร
- Dimensional Worship : บูชาข้ามมิติ
- Relentless Industrialists : นักอุตสาหกรรมที่ไม่หยุดยั้ง
- Sovereign Guardianship : ผู้พิทักษ์อธิปไตย

**Comment by pongmadee** [comment]
ok ครับผม

**Comment by PhakphumV** [comment]
![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/ca22c958-9c04-400c-b389-db55a9b08667)

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/61e68c15-88ff-4f68-94f3-e24a4faf73bc)

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/0fe7efe9-51ea-4b6b-a9da-5d47e1d9678c)

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/7fcb1516-9467-4ef2-91ad-040e1217aae5)

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/927b8afa-caad-4b53-acab-51db55a9c1cc)

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/df958104-859a-48ba-9a5e-4599e50aab6b)

ตรวจสอบเรียบร้อยนะครับ issue นับเป็นการแปลเฉพาะ civic สำหรับระบอบการปกครองธรรมดา ไปก่อนนะครับ
เดี๋ยวเปิด issue ใหม่ สำหรับ civic ที่เหลือ เป็นกลุ่มๆไป

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/f0eae8fd-5e31-4d24-95cf-41e22713cef0)
