### ISSUE TITLE
Missing Translation - คำว่า "Repeal" ในมติ ประชาคมกาแล็กติก

### ISSUE THREAD

**Issue by PhakphumV** [pongmadee/Stellaris-Thai-Translation-MOD#6]
Mod version 0.71.5

แนะนำคำศัพท์แทนคำว่า Repeal ในมติ ของ ประชาคมกาแล็กติก นะครับ
ใช้เป็นคำว่า "เพิกถอน" หรือ "ยกเลิก" ได้นะครับ

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/cca0bd36-56ba-4e10-9a72-2905ba560610)

**Comment by pongmadee** [comment]
ok ครับ

**Comment by PhakphumV** [comment]
คำแปลขึ้นแล้วครับ
