### ISSUE TITLE
 Missing translation - มติเรื่อง การแปรรูปกลาโหม

### ISSUE THREAD

**Issue by PhakphumV** [pongmadee/Stellaris-Thai-Translation-MOD#8]
Mod version 0.71.5

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/5a21473a-ac83-489f-aaac-318c80ac4107)

- Security Contractors
- High Consequence Protection
- Neutral Defenders
- Galactic Risk Management
- Corporate Peacekeeping

เดี๋ยวมาช่วยแปลให้นะครับ

**Comment by PhakphumV** [comment]
คำแปลของแต่ละคำ พร้อมแหล่งอ้างอิงนะครับ
- Security Contractors : ผู้รับเหมารักษาความปลอดภัย
อันนี้แปลตรงตัวจาก Google Translate เลยครับ ไม่น่าจะติดอะไร

- High Consequence Protection : การคุ้มครองสิ่งที่มีผลกระทบสูง
ลองใช้ Google Translate แล้วมันแปลว่า "การป้องกันผลที่ตามมาสูง" แต่มันงงๆนิดนึง เลยไปหาข้อมูลวลีนี้ดู
เป็นโครงการหรือบริการคุ้มกันสิ่งของหรือบุคคลที่หาถูกโจรกรรมหรือหาย มีผลกระทบสูง เช่น หัวรบนิวเคลียร์ สารเคมีอันตรายต่างๆ ฯลฯ
โดยให้ผู้รับเหมารักษาความปลอดภัย หรือ PMC (Private military company) เป็นผู้ดูแลความปลอดภัยคุ้มกันสิ่งนั้นตามที่ได้รับมอบหมาย

อ้างอิง
https://www.constellis.com/services/security/high-consequence-protection/

- Neutral Defenders : ผู้พิทักษ์ที่เป็นกลาง
อันนี้แปลตรงตัวจาก Google Translate เลยครับ ไม่น่าจะติดอะไร

- Galactic Risk Management : บริหารความเสี่ยงกาแลคติก

- Corporate Peacekeeping : บริษัทรักษาสันติภาพ

**Comment by pongmadee** [comment]
ขอบคุณครับ

**Comment by PhakphumV** [comment]
![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/2585f062-78c7-4a9c-b24f-1d06d21a9ffe)

ตรวจสอบเรียบร้อยครับ
