### ISSUE TITLE
Missing translation - มติกลุ่ม Suzerains and Sovereignty

### ISSUE THREAD

**Issue by PhakphumV** [pongmadee/Stellaris-Thai-Translation-MOD#9]
Mod version 0.71.5

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/4026be58-a2a7-4830-8528-033b993b9639)

มีคำศัพท์ที่ยังไม่แปลดังนี้

## หัวข้อกลุ่ม
- Suzerains and Sovereignty

## มติเรื่อง คำสั่งอินเตอร์กาแล็กติก
- Regulated Growth
- Ensured Sovereignty
- A Voice for All

## มติเรื่อง การตรวจตราดูแลระบบราชการ
- Administrative Insight
- Borderless Authority
- Personal Oversight

**Comment by PhakphumV** [comment]
คำแปลหัวข้อกลุ่ม Suzerains and Sovereignty

คำว่า Suzerains แปลตาม Google Translate ว่า "นริศ" แต่ศัพท์นี้ไม่ค่อยเป็นที่รู้จักกัน

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/1352799a-5a94-4fec-afdf-a0cdb7d97953)

คำว่า Sovereignty แปลว่า "อธิปไตย" หรือ "อำนาจอธิปไตย"

ซึ่งถ้าแปลให้มันสอดคล้องกับเนื้อหามติในกลุ่มนี้ น่าจะแปลเป็น

"รัฐเหนือหัวและอำนาจอธิปไตย"

น่าจะเข้าใจได้ตรงกว่านะครับ

**Comment by PhakphumV** [comment]
คำแปลต่อ

## มติเรื่อง คำสั่งอินเตอร์กาแล็กติก
- Regulated Growth : ควบคุมการเติบโต
- Ensured Sovereignty : รองรับอธิปไตย
- A Voice for All : เสียงสำหรับทุกคน

**Comment by PhakphumV** [comment]
คำแปลต่อ
## มติเรื่อง การตรวจตราดูแลระบบราชการ

- Administrative Insight : ข้อมูลเชิงลึกด้านการบริหาร
- Borderless Authority : อำนาจไร้พรมแดน
- Personal Oversight : การกำกับดูแลส่วนบุคคล

**Comment by pongmadee** [comment]
โอ...ขอบใจมาก เดี๋ยวช่วงลดราคาน่าจะจัด dlc overlord เพิ่มซะแล้ว 
ปล. โทษทีครับ บางทีผมตอบช้าหน่อย แต่ผมพยายามเข้ามาดูบ่อยๆครับ แล้วจะรวบรวมข้อมูลและอัปเดตวันเสาร์-อาทิตย์ครับ ส่วนวันธรรมดาก็ช่วงเย็นๆค่ำๆหลังกลับถึงบ้าน(ถ้าไม่ง่วงซะก่อนนะ55+)

**Comment by PhakphumV** [comment]
![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/4ab92313-a877-435e-90b1-262504e3a69d)

![image](https://github.com/pongmadee/Stellaris-Thai-Translation-MOD/assets/35300139/c481a9b9-993b-4757-93c9-bcfb27128e2c)

ตรวจสอบเรียบร้อยครับ
